# Generated by Django 3.1.1 on 2020-11-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=50, unique=True)),
                ('generator', models.CharField(max_length=100)),
                ('generated', models.CharField(max_length=21)),
                ('rpa', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('library', models.TextField(null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('doc', models.TextField(null=True)),
                ('parent_id', models.IntegerField(null=True)),
                ('timeout', models.TextField(null=True)),
                ('status', models.CharField(max_length=10)),
                ('starttime', models.CharField(max_length=21)),
                ('endtime', models.CharField(max_length=21)),
                ('elapsed', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('source', models.TextField(null=True)),
                ('doc', models.TextField(null=True)),
                ('msg', models.TextField(null=True)),
                ('parent_id', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=10)),
                ('starttime', models.CharField(max_length=21)),
                ('endtime', models.CharField(max_length=21)),
                ('elapsed', models.IntegerField(null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.execution')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('doc', models.TextField(null=True)),
                ('msg', models.TextField(null=True)),
                ('timeout', models.TextField(null=True)),
                ('status', models.CharField(max_length=10)),
                ('starttime', models.CharField(max_length=21)),
                ('endtime', models.CharField(max_length=21)),
                ('elapsed', models.IntegerField(null=True)),
                ('critical', models.CharField(max_length=5)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.suite')),
            ],
        ),
        migrations.CreateModel(
            name='TestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_pass', models.CharField(max_length=10)),
                ('_fail', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('elapsed', models.IntegerField(null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.execution')),
            ],
        ),
        migrations.CreateModel(
            name='TagStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_pass', models.CharField(max_length=10)),
                ('_fail', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('elapsed', models.IntegerField(null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.execution')),
            ],
        ),
        migrations.CreateModel(
            name='SuiteStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('_pass', models.CharField(max_length=10)),
                ('_fail', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('text', models.TextField()),
                ('elapsed', models.IntegerField(null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.execution')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=21)),
                ('level', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.suite'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.test'),
        ),
        migrations.CreateModel(
            name='ExecutionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('timestamp', models.CharField(max_length=21)),
                ('text', models.TextField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.execution')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.TextField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg', models.TextField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.keyword')),
            ],
        ),
    ]
