# Generated by Django 3.1.1 on 2020-11-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='argument',
            table='keyword_arguments',
        ),
        migrations.AlterModelTable(
            name='assign',
            table='keyword_assigns',
        ),
        migrations.AlterModelTable(
            name='execution',
            table='executions',
        ),
        migrations.AlterModelTable(
            name='executionerror',
            table='execution_errors',
        ),
        migrations.AlterModelTable(
            name='keyword',
            table='keywords',
        ),
        migrations.AlterModelTable(
            name='keywordtag',
            table='keyword_tags',
        ),
        migrations.AlterModelTable(
            name='message',
            table='keyword_messages',
        ),
        migrations.AlterModelTable(
            name='suite',
            table='suites',
        ),
        migrations.AlterModelTable(
            name='suitestatistics',
            table='suite_statistics',
        ),
        migrations.AlterModelTable(
            name='tagstatistics',
            table='tag_statistics',
        ),
        migrations.AlterModelTable(
            name='test',
            table='tests',
        ),
        migrations.AlterModelTable(
            name='teststatistics',
            table='test_statistics',
        ),
        migrations.AlterModelTable(
            name='testtag',
            table='test_tags',
        ),
    ]
